# Generated by Django 4.2.6 on 2023-11-02 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('science_conf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='guests',
            field=models.ManyToManyField(through='science_conf_app.ConferenceAttendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conferenceattendance',
            name='form_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='form_author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='conferencecomments',
            name='type',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, null=True),
        ),
    ]
