# Generated by Django 4.2.6 on 2023-11-03 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('science_conf_app', '0002_conference_guests_conferenceattendance_form_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceattendance',
            name='role',
            field=models.CharField(choices=[('AT', 'Attendee'), ('SP', 'Speaker'), ('OG', 'Organiser'), ('SO', 'Sponsor')], default='AT', max_length=2),
        ),
        migrations.AlterField(
            model_name='conferencelectures',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='science_conf_app.conferenceattendance'),
        ),
    ]
