# Generated by Django 4.2.6 on 2023-11-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('science_conf_app', '0003_alter_conferenceattendance_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceattendance',
            name='date_arrive',
        ),
        migrations.RemoveField(
            model_name='conferenceattendance',
            name='date_leave',
        ),
    ]
