# Generated by Django 4.2.6 on 2023-12-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_marketplace_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='salonowner',
            name='user',
        ),
    ]
