# Generated by Django 4.2.6 on 2023-12-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_marketplace_app', '0002_remove_customer_user_remove_salonowner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonappointment',
            name='payment',
        ),
        migrations.AddField(
            model_name='salonservice',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
