# Generated by Django 4.2.6 on 2023-10-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner_car',
        ),
    ]
