# Generated by Django 4.2.6 on 2023-10-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_remove_car_owner_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carowner',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='carownership',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='driverslicence',
            options={'ordering': ['id']},
        ),
    ]
