# Generated by Django 4.2.6 on 2023-10-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_alter_carowner_options_alter_carownership_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ManyToManyField(through='project_first_app.CarOwnership', to='project_first_app.carowner'),
        ),
        migrations.AddField(
            model_name='carowner',
            name='cars',
            field=models.ManyToManyField(through='project_first_app.CarOwnership', to='project_first_app.car'),
        ),
    ]
