# Generated by Django 4.2.6 on 2023-10-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0005_alter_carowner_managers_carowner_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='carowner',
            name='name',
        ),
        migrations.AlterField(
            model_name='carowner',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
