# Generated by Django 4.2.6 on 2023-10-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0008_remove_car_owner_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
